### ISSUE TITLE
Improve Dropdown Menu Safety by Color-Coding and Reorganizing Options

### ISSUE THREAD

**Issue by tradebigshort** [subspace/staking-interface#71]
### Issue Description
I have noticed a potential usability issue in our dropdown menu, particularly involving the options 'Deregister', 'AddFunds', and 'Withdraw'. On two occasions, I accidentally selected 'Deregister' instead of 'AddFunds'. This mistake seems to stem from the proximity of these critical options in the menu and could easily happen to other users, especially under conditions of haste or fatigue.

### Proposed Solution
To address this issue, I propose two key enhancements to the dropdown menu:

1. **Reordering of Options**: Move the 'Deregister' option to the bottom of the dropdown menu. This creates a clear physical separation between frequently used actions ('AddFunds' and 'Withdraw') and a significant, less frequently used action ('Deregister').

2. **Color Coding Critical Options**: Apply a distinct color, such as red, to the 'Deregister' option. This visual cue will instantly alert users to the seriousness of this action, reducing the likelihood of accidental selection.

### Expected Benefits
- **Minimizes Accidental Selections**: The combination of reordering and color-coding will significantly reduce the risk of users inadvertently choosing the 'Deregister' option.
- **Enhances User Experience**: These changes will make the dropdown menu more intuitive and user-friendly, particularly for quick navigation.
- **Prevents User Frustration and Potential Errors**: By clearly distinguishing critical actions, we can prevent the frustration and consequences associated with unintended deregistration.

### Additional Information
- Attached is a screenshot showing the current layout of the dropdown menu.
- 
![image (1)](https://github.com/subspace/staking-interface/assets/46727466/d19154f7-e940-439a-84ad-683bd9a4c102)

- These suggestions are based on personal experience, and I believe they could greatly benefit all users of our interface.

Your feedback and any additional suggestions on this proposal would be highly appreciated.

Thank you,
tradershort

**Comment by marc-aurele-besner** [comment]
Thank you for this constructive feedback, this make a lot of sense, I'll do the changes shortly 💪

**Comment by tradebigshort** [comment]
Excelent !! I have already made this error twice, press Deregister !

Thank you !

**Comment by tradebigshort** [comment]
Good ! it's working ! and so much better !!
