### ISSUE TITLE
Add 'Rank' Column to Improve Data Readability in TotalStake Section

### ISSUE THREAD

**Issue by tradebigshort** [subspace/staking-interface#72]
### Feature Request
**Summary:** Introduce a 'Rank' column to the TotalStake section of our interface for better clarity and organization of stake rankings.

**Details:** In the current interface, while viewing the stake distribution, it can be challenging to determine the rank of each nominator or operator quickly. To enhance user experience and data readability, I propose adding a 'Rank' column. This would provide users with immediate visibility into how each entity ranks relative to others in terms of their total stake.

**Benefits:**
- Quick reference for users to understand the ranking order.
- Improved navigation and data assessment experience.
- More structured data presentation, aiding in data analysis tasks.

**Current Layout:** Attached is an image that displays the current layout of the section in question.
![rank](https://github.com/subspace/staking-interface/assets/46727466/a337ad18-6588-41bc-b0af-6f0dce7b6208)

**Proposed Change:** The new 'Rank' column would be placed at the beginning of the table, providing a sequential number ranking based on the sorted order of the TotalStake.

Looking forward to further discussion and feedback on this enhancement.

Best,
tradershort

**Comment by marc-aurele-besner** [comment]
To confirm, we are talking about adding a column with the index of each row. This way, no matter the order you chose to order the list or the direction of the order, that first column will always go from 1 to the end, similar than on Excel or google sheet. Correct?

**Comment by tradebigshort** [comment]
Yes, that's correct. The idea is to add a static index column to the table, much like the row numbers in Excel or Google Sheets. This column will sequentially number the rows from 1 onwards, providing a clear and consistent reference point regardless of how the data is sorted or filtered in other columns. This can greatly enhance the readability and navigation of the table for users.
